import Header from './Header'
import Footer from './Footer'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen h-full flex flex-col content-between bg-slate-50">
        <Header/>
        <div className="flex-1 max-w-4xl mx-auto">
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  )
}
